### ISSUE TITLE
Do we need this?

### ISSUE THREAD

**Issue by bookofportals** [AgoraNomic/Agora-Interface#1]
@PubliusScriboniusScholasticus, my understanding is that this project is dead. It's also essentially empty. May I delete it?

**Comment by PubliusScriboniusScholasticus** [comment]
Yes, that's fine. This was planned to be along the lines of what o is doing, so this can definitely be removed.
----
Publius Scribonius Scholasticus
p.scribonius.scholasticus@gmail.com

**Comment by ojacobson** [comment]
I plan on kicking ojacobson/cadastre and ojacobson/cadastre-cli over to the AgoraNomic organization once they're a little further along (and I'm more than happy to take pull requests now, if you have ideas), too.

**Comment by bookofportals** [comment]
Deleting.
